	/// one of them:
#define I2C_TASK_SCAN_INPUT
// #define I2C_TASK_IRQ_INPUT

#define TASK_STACK_SIZE 1024

#define GPIO_BUTTON1_PORT  GPIO1
#define GPIO_BUTTON1_PIN   0U
#define GPIO_BUTTON2_PORT  GPIO1
#define GPIO_BUTTON2_PIN   1U
#define GPIO_BUTTON3_PORT  GPIO1
#define GPIO_BUTTON3_PIN   3U
#define GPIO_BUTTON4_PORT  GPIO1
#define GPIO_BUTTON4_PIN   5U

#define I2C_GPIO_SX1509_IRQ_PORT GPIO_BUTTON4_PORT
#define I2C_GPIO_SX1509_IRQ_PIN  GPIO_BUTTON4_PIN

#define master_task_PRIORITY (configMAX_PRIORITIES - 2)
